[general]
import = ["~/.config/alacritty/tokyo-night.toml"]

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "ComicCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ComicCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ComicCode Nerd Font"
style = "Italic"

[font.normal]
family = "ComicCode Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = false

[window]
dynamic_padding = false
dynamic_title = true
opacity = 1
decorations = "None"

[scrolling]
history = 3023


[mouse]
hide_when_typing = true

[bell]
duration = 0

[keyboard]
bindings = [
  { key = "C",       mods = "Control|Shift", action = "Copy"  },
  { key = "V",       mods = "Control|Shift", action = "Paste" },
  { key = "N",       mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Equals",  mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus",   mods = "Control",       action = "DecreaseFontSize" },
  { key = "Key0",    mods = "Control",       action = "ResetFontSize"    },
  { key = "Enter",   mods = "Shift",         chars = "\n" },
]
